CREATE TABLE users (
  id integer primary key generated by default as identity,
  username text not null unique,
  name text not null,
  password text not null,
  zipcode numeric not null,
  date_registered timestamptz default now() NOT NULL
);