CREATE TABLE activities (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  zipcode numeric NOT NULL,
  user_id INTEGER REFERENCES "users"(id),
  start_time timestamptz NOT NULL,
  end_time timestamptz NOT NULL
);